#ifndef PQC_FRODOKEM_976_PARAMETERS_H
#define PQC_FRODOKEM_976_PARAMETERS_H

#define FRODOKEM_CRYPTO_SECRETKEYBYTES 31296
#define FRODOKEM_CRYPTO_PUBLICKEYBYTES 15632
#define FRODOKEM_CRYPTO_BYTES 24
#define FRODOKEM_CRYPTO_CIPHERTEXTBYTES 15744
#define FRODOKEM_CRYPTO_ALGNAME "eFrodoKEM-976"

#define PARAMS_N 976
#define PARAMS_NBAR 8
#define PARAMS_LOGQ 16
#define PARAMS_Q (1 << PARAMS_LOGQ)
#define PARAMS_EXTRACTED_BITS 3
#define PARAMS_STRIPE_STEP 8
#define PARAMS_PARALLEL 4
#define BYTES_SEED_A 16
#define BYTES_MU ((PARAMS_EXTRACTED_BITS * PARAMS_NBAR * PARAMS_NBAR) / 8)
#define BYTES_PKHASH FRODOKEM_CRYPTO_BYTES

#define CRYPTO_SECRETKEYBYTES FRODOKEM_CRYPTO_SECRETKEYBYTES
#define CRYPTO_PUBLICKEYBYTES FRODOKEM_CRYPTO_PUBLICKEYBYTES
#define CRYPTO_BYTES FRODOKEM_CRYPTO_BYTES
#define CRYPTO_CIPHERTEXTBYTES FRODOKEM_CRYPTO_CIPHERTEXTBYTES
#define CRYPTO_ALGNAME FRODOKEM_CRYPTO_ALGNAME

#endif
