#ifndef LACLIGHT_PARAMS_H
#define LACLIGHT_PARAMS_H

#include "polarlac.h"

#define LACLIGHT_LEVEL POLARLAC_LEVEL_LIGHT
#define LACLIGHT_NAME "LAC_LIGHT"
#define LACLIGHT_DIM_N 512
#define LACLIGHT_DIM_N_2 256
#define LACLIGHT_DIM_N_4 128
#define LACLIGHT_DIM_N_8 64
#define LACLIGHT_SEED_LEN 32
#define LACLIGHT_PK_LEN 544
#define LACLIGHT_SK_PART_LEN LACLIGHT_DIM_N
#define LACLIGHT_SK_LEN 576
#define LACLIGHT_MESSAGE_LEN 16
#define LACLIGHT_CIPHER_LEN 576
#define LACLIGHT_C2_VEC_NUM 256
#define LACLIGHT_NUM_ONE 128
#define LACLIGHT_HASH_TYPE "SHA256"
#define LACLIGHT_SAMPLE_LEN 590
#define LACLIGHT_DATA_LEN 16
#define LACLIGHT_CODE_LEN 32
#define LACLIGHT_POLAR_N 256
#define LACLIGHT_POLAR_LOG_N 8
#define LACLIGHT_POLAR_K 128
#define LACLIGHT_POLAR_ECC_BYTES 32
#define LACLIGHT_SECRETKEYBYTES (LACLIGHT_SK_LEN + LACLIGHT_PK_LEN)
#define LACLIGHT_PUBLICKEYBYTES LACLIGHT_PK_LEN
#define LACLIGHT_BYTES LACLIGHT_MESSAGE_LEN
#define LACLIGHT_SESSIONBYTES 32
#define LACLIGHT_CIPHERTEXTBYTES LACLIGHT_CIPHER_LEN
#define LACLIGHT_SEEDBYTES LACLIGHT_SEED_LEN
#define LACLIGHT_NTTQ 8380417
#define LACLIGHT_NTT_INV_Q 58728449
#define LACLIGHT_NTT_INV_N 41978
#define LACLIGHT_NTT_K 0
#define LACLIGHT_BITLEN_Q 24
#define LACLIGHT_B_Q 25
#define LACLIGHT_INVERSE_N 8364049
#define LACLIGHT_INVERSE_N_BETA 8191
#define LACLIGHT_NTT_OMEGA_COUNT 4
#define LACLIGHT_NTT_OMEGA M512_LAC

extern const polarlac_params_t laclight_params;

#endif
