#ifndef POLARLAC_PARAMS_H
#define POLARLAC_PARAMS_H

#include "polarlac.h"

extern const polarlac_params_t laclight_params;
extern const polarlac_params_t lac128_params;
extern const polarlac_params_t lac256_params;
extern const polarlac_params_t *const polarlac_params_list[POLARLAC_LEVEL_COUNT];
extern polarlac_level_t g_polarlac_level;

#define POLARLAC_PARAMS polarlac_current_params()
#define POLARLAC_PARAM_LEVEL (POLARLAC_PARAMS->level)
#define POLARLAC_PARAM_NAME (POLARLAC_PARAMS->name)
#define POLARLAC_PARAM_DIM_N (POLARLAC_PARAMS->dim_n)
#define POLARLAC_PARAM_DIM_N_2 (POLARLAC_PARAMS->dim_n_2)
#define POLARLAC_PARAM_DIM_N_4 (POLARLAC_PARAMS->dim_n_4)
#define POLARLAC_PARAM_DIM_N_8 (POLARLAC_PARAMS->dim_n_8)
#define POLARLAC_PARAM_SEED_LEN (POLARLAC_PARAMS->seed_len)
#define POLARLAC_PARAM_PK_LEN (POLARLAC_PARAMS->pk_len)
#define POLARLAC_PARAM_SK_PART_LEN (POLARLAC_PARAMS->sk_part_len)
#define POLARLAC_PARAM_SK_LEN (POLARLAC_PARAMS->sk_len)
#define POLARLAC_PARAM_MESSAGE_LEN (POLARLAC_PARAMS->message_len)
#define POLARLAC_PARAM_CIPHER_LEN (POLARLAC_PARAMS->cipher_len)
#define POLARLAC_PARAM_C2_VEC_NUM (POLARLAC_PARAMS->c2_vec_num)
#define POLARLAC_PARAM_NUM_ONE (POLARLAC_PARAMS->num_one)
#define POLARLAC_PARAM_HASH_TYPE (POLARLAC_PARAMS->hash_type)
#define POLARLAC_PARAM_SAMPLE_LEN (POLARLAC_PARAMS->sample_len)
#define POLARLAC_PARAM_DATA_LEN (POLARLAC_PARAMS->data_len)
#define POLARLAC_PARAM_CODE_LEN (POLARLAC_PARAMS->code_len)
#define POLARLAC_PARAM_POLAR_N (POLARLAC_PARAMS->polar_n)
#define POLARLAC_PARAM_POLAR_LOG_N (POLARLAC_PARAMS->polar_log_n)
#define POLARLAC_PARAM_POLAR_K (POLARLAC_PARAMS->polar_k)
#define POLARLAC_PARAM_POLAR_ECC_BYTES (POLARLAC_PARAMS->polar_ecc_bytes)
#define POLARLAC_PARAM_POLAR_INFO_NODES (POLARLAC_PARAMS->polar_info_nodes)
#define POLARLAC_PARAM_POLAR_LAMBDA_OFFSET (POLARLAC_PARAMS->polar_lambda_offset)
#define POLARLAC_PARAM_POLAR_LLR_LAYER_VEC (POLARLAC_PARAMS->polar_llr_layer_vec)
#define POLARLAC_PARAM_POLAR_BIT_LAYER_VEC (POLARLAC_PARAMS->polar_bit_layer_vec)
#define POLARLAC_PARAM_LLR_TABLE (POLARLAC_PARAMS->llr_table)
#define POLARLAC_PARAM_SECRETKEYBYTES (POLARLAC_PARAMS->secret_key_bytes)
#define POLARLAC_PARAM_PUBLICKEYBYTES (POLARLAC_PARAMS->public_key_bytes)
#define POLARLAC_PARAM_BYTES (POLARLAC_PARAMS->message_bytes)
#define POLARLAC_PARAM_SESSIONBYTES (POLARLAC_PARAMS->session_bytes)
#define POLARLAC_PARAM_CIPHERTEXTBYTES (POLARLAC_PARAMS->ciphertext_bytes)
#define POLARLAC_PARAM_SEEDBYTES (POLARLAC_PARAMS->seed_bytes)
#define POLARLAC_PARAM_NTTQ (POLARLAC_PARAMS->ntt_q)
#define POLARLAC_PARAM_NTT_INV_Q (POLARLAC_PARAMS->ntt_inv_q)
#define POLARLAC_PARAM_NTT_INV_N (POLARLAC_PARAMS->ntt_inv_n)
#define POLARLAC_PARAM_NTT_K (POLARLAC_PARAMS->ntt_k)
#define POLARLAC_PARAM_BITLEN_Q (POLARLAC_PARAMS->bitlen_q)
#define POLARLAC_PARAM_B_Q (POLARLAC_PARAMS->b_q)
#define POLARLAC_PARAM_INVERSE_N (POLARLAC_PARAMS->inverse_n)
#define POLARLAC_PARAM_INVERSE_N_BETA (POLARLAC_PARAMS->inverse_n_beta)
#define POLARLAC_PARAM_NTT_OMEGA_COUNT (POLARLAC_PARAMS->ntt_omega_count)
#define POLARLAC_PARAM_NTT_OMEGA (POLARLAC_PARAMS->ntt_omega)
#define POLARLAC_PARAM_NTT_HW_CONFIG (POLARLAC_PARAMS->ntt_hw_config)

#define STRENGTH POLARLAC_PARAM_NAME

#endif
