#ifndef PQC_FRODOKEM_640_PARAMETERS_H
#define PQC_FRODOKEM_640_PARAMETERS_H

#define FRODOKEM_CRYPTO_SECRETKEYBYTES 19888
#define FRODOKEM_CRYPTO_PUBLICKEYBYTES 9616
#define FRODOKEM_CRYPTO_BYTES 16
#define FRODOKEM_CRYPTO_CIPHERTEXTBYTES 9720
#define FRODOKEM_CRYPTO_ALGNAME "eFrodoKEM-640"

#define PARAMS_N 640
#define PARAMS_NBAR 8
#define PARAMS_LOGQ 15
#define PARAMS_Q (1 << PARAMS_LOGQ)
#define PARAMS_EXTRACTED_BITS 2
#define PARAMS_STRIPE_STEP 8
#define PARAMS_PARALLEL 4
#define BYTES_SEED_A 16
#define BYTES_MU ((PARAMS_EXTRACTED_BITS * PARAMS_NBAR * PARAMS_NBAR) / 8)
#define BYTES_PKHASH FRODOKEM_CRYPTO_BYTES

#define CRYPTO_SECRETKEYBYTES FRODOKEM_CRYPTO_SECRETKEYBYTES
#define CRYPTO_PUBLICKEYBYTES FRODOKEM_CRYPTO_PUBLICKEYBYTES
#define CRYPTO_BYTES FRODOKEM_CRYPTO_BYTES
#define CRYPTO_CIPHERTEXTBYTES FRODOKEM_CRYPTO_CIPHERTEXTBYTES
#define CRYPTO_ALGNAME FRODOKEM_CRYPTO_ALGNAME

#endif
