#ifndef PQC_HQC_PARAMETERS_H
#define PQC_HQC_PARAMETERS_H

#include "api.h"

#define CEIL_DIVIDE(a, b) (((a) / (b)) + ((a) % (b) == 0 ? 0 : 1))
#define BITMASK(a, size) ((uint64_t)((1ULL << ((a) % (size))) - 1ULL))

#define PARAM_N 17669
#define PARAM_N1 46
#define PARAM_N2 384
#define PARAM_N1N2 17664
#define PARAM_OMEGA 66
#define PARAM_OMEGA_E 75
#define PARAM_OMEGA_R 75
#define PARAM_SECURITY 128
#define PARAM_SECURITY_BYTES 16
#define PARAM_DFR_EXP 128

#define SECRET_KEY_BYTES CRYPTO_SECRETKEYBYTES
#define PUBLIC_KEY_BYTES CRYPTO_PUBLICKEYBYTES
#define SHARED_SECRET_BYTES CRYPTO_BYTES
#define CIPHERTEXT_BYTES CRYPTO_CIPHERTEXTBYTES

#define VEC_N_SIZE_BYTES CEIL_DIVIDE(PARAM_N, 8)
#define VEC_K_SIZE_BYTES PARAM_K
#define VEC_N1_SIZE_BYTES PARAM_N1
#define VEC_N1N2_SIZE_BYTES CEIL_DIVIDE(PARAM_N1N2, 8)

#define VEC_N_SIZE_64 CEIL_DIVIDE(PARAM_N, 64)
#define VEC_N1_SIZE_64 CEIL_DIVIDE(PARAM_N1, 8)
#define VEC_N1N2_SIZE_64 CEIL_DIVIDE(PARAM_N1N2, 64)

#define PARAM_DELTA 15
#define PARAM_M 8
#define PARAM_GF_POLY 0x11D
#define PARAM_GF_MUL_ORDER 255
#define PARAM_K 16
#define PARAM_G 31
#define PARAM_FFT 4

#define RS_POLY_COEFS                                                                                                \
    89, 69, 153, 116, 176, 117, 111, 75, 73, 233, 242, 233, 65, 210, 21, 139, 103, 173, 67, 118,                   \
        105, 210, 174, 110, 74, 69, 228, 82, 255, 181, 1

#define SEED_BYTES 32
#define SALT_BYTES 16
#ifndef HQC_SEED_BYTES
#define HQC_SEED_BYTES SEED_BYTES
#endif
#ifndef HQC_SALT_BYTES
#define HQC_SALT_BYTES SALT_BYTES
#endif
#ifndef HQC_SHARED_SECRET_BYTES
#define HQC_SHARED_SECRET_BYTES SHARED_SECRET_BYTES
#endif

#define PARAM_N_MU 243079ULL
#define UTILS_REJECTION_THRESHOLD 16767881

#define HQC_MAX_N PARAM_N
#define HQC_MAX_N1 PARAM_N1
#define HQC_MAX_N2 PARAM_N2
#define HQC_MAX_N1N2 PARAM_N1N2
#define HQC_MAX_OMEGA_R PARAM_OMEGA_R
#define HQC_MAX_SECURITY_BYTES PARAM_SECURITY_BYTES
#define HQC_MAX_DELTA PARAM_DELTA
#define HQC_MAX_K PARAM_K
#define HQC_MAX_G PARAM_G
#define HQC_MAX_FFT PARAM_FFT
#define HQC_MAX_VEC_N_SIZE_BYTES VEC_N_SIZE_BYTES
#define HQC_MAX_VEC_N1N2_SIZE_BYTES VEC_N1N2_SIZE_BYTES
#define HQC_MAX_VEC_N_SIZE_64 VEC_N_SIZE_64
#define HQC_MAX_VEC_N1_SIZE_64 VEC_N1_SIZE_64
#define HQC_MAX_VEC_N1N2_SIZE_64 VEC_N1N2_SIZE_64
#define HQC_MAX_PUBLIC_KEY_BYTES PUBLIC_KEY_BYTES
#define HQC_MAX_SECRET_KEY_BYTES SECRET_KEY_BYTES
#define HQC_MAX_CIPHERTEXT_BYTES CIPHERTEXT_BYTES

#endif
