#ifndef PQC_HQC_HQC1_LEVEL_H
#define PQC_HQC_HQC1_LEVEL_H

#define HQC_LEVEL_NAMESPACE(suffix) hqc1_##suffix

#define CRYPTO_ALGNAME "HQC-1"
#define CRYPTO_SECRETKEYBYTES 2321
#define CRYPTO_PUBLICKEYBYTES 2241
#define CRYPTO_BYTES 32
#define CRYPTO_CIPHERTEXTBYTES 4433

#endif
