#ifndef PQC_HQC_HQC3_LEVEL_H
#define PQC_HQC_HQC3_LEVEL_H

#define HQC_LEVEL_NAMESPACE(suffix) hqc3_##suffix

#define CRYPTO_ALGNAME "HQC-3"
#define CRYPTO_SECRETKEYBYTES 4602
#define CRYPTO_PUBLICKEYBYTES 4514
#define CRYPTO_BYTES 32
#define CRYPTO_CIPHERTEXTBYTES 8978

#endif
