#ifndef PQC_HQC_HQC5_LEVEL_H
#define PQC_HQC_HQC5_LEVEL_H

#define HQC_LEVEL_NAMESPACE(suffix) hqc5_##suffix

#define CRYPTO_ALGNAME "HQC-5"
#define CRYPTO_SECRETKEYBYTES 7333
#define CRYPTO_PUBLICKEYBYTES 7237
#define CRYPTO_BYTES 32
#define CRYPTO_CIPHERTEXTBYTES 14421

#endif
